---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create EC2
    ec2_instance:
      region: "{{ region='us-east-1' }}"
      key_name: "{{ 'okkk' }}"
      security_group: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ security_group }}', region='us-east-1') }}"
      image_id: "{{ 'ami-0cf10cdf9fcd62d37' }}"
      instance_type: "{{ instance_type }}"
      region: "us-east-1"
      vpc_subnet_id: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ vpc_subnet_id }}', region='us-east-1') }}"
      instance_role: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ instance_role }}', region='us-east-1') }}"
      wait: true
      volumes:
        - device_name: /dev/xvda
          ebs:
            volume_type: gp2
            volume_size: "{{ root_volume_size }}"
            delete_on_termination: true
            encrypted: true
      name: "{{ instance_name }}"
      tags:
        created_by: "{{ created_by }}"
        Owner: "{{ Owner }}"
        App_Name: "{{ App_Name }}"
        Cost_Center: "{{ Cost_Center }}"
        Business_Unit: "{{ Business_Unit }}"
      user_data: |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        systemctl enable httpd.service
        sudo cd /var/www/html
        echo '<h1>Ansible Tower Project Done and Verified<h1>' > /var/www/html/index.html
        sudo systemctl start httpd.service

#  - debug:
#      msg: ec2_instance
#  - debug:
#      msg: "{{ ec2.results[0].instance_ids }}"
